### ISSUE TITLE
Realex Payments in Magento 2.3: «Your transaction has been successful but there was a problem connecting back to the merchant's web site»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [tradefurniturecompany/core#16]
![04](https://user-images.githubusercontent.com/83204/66506150-99811380-eaee-11e9-88e2-12ece71528f4.png)

**Comment by dmitrii-fediuk** [comment]
Fixed in `app/code/Customweb/RealexCw/Controller/Endpoint/Index.php`

**Comment by mitesh-lr** [comment]
@dmitry-fedyuk Could you please place the source code of the file or let me know where is the issue as I am also facing same problem in live site in magento2.4.2 in realex payment.

**Comment by dmitrii-fediuk** [comment]
To replicate a solution made by me for another customer, hire me in Upwork: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
