### ISSUE TITLE
«Declaration of FishPig\WordPress\Model\Image::getContent() must be compatible with FishPig\WordPress\Model\Post::getContent($context = 'default')»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [tradefurniturecompany/core#23]
![01](https://user-images.githubusercontent.com/83204/72340851-1c6bc880-36f3-11ea-9a39-fabfffd744b6.png)

**Comment by dmitrii-fediuk** [comment]
app/code/FishPig/WordPress/Model/Image.php:189

**Comment by rvoronovmeticulosity** [comment]
@dmitry-fedyuk  How was it resolved? I have the same issue on the project after upgrading from 2.2.* to 2.3.*

**Comment by dmitrii-fediuk** [comment]
You can hire me on Upwork: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro).
I do not consult for free.
